apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: 857900057298.dkr.ecr.ap-southeast-1.amazonaws.com/nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
